version: '3'
services:
  web: 
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build: .
    ports:
      - "80:80"
    volumes:
      - source_sync:/var/www/html:nocopy
    links:
      - db:db
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
            - ./.data/db:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306" 
  phpmyadmin:
      container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
          - "8080:80"


# that the important thing
volumes:
  source_sync:
    external: 
      name: ${COMPOSE_PROJECT_NAME}_sync