version: '2'
services:
  web: 
    container_name: projectName_web
    build: .
    ports:
      - "80:80"
    volumes:
      - appcode-native-osx-sync:/var/www/html:nocopy
    links:
      - db:db
  db:
    container_name: projectName_db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
            - ./.data/db:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306" 
  phpmyadmin:
      container_name: projectName_phpmyadmin
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
          - "8080:80"



# this is our development docker-compose building on top of the production docker-compose, just mounting
# the sync image - not redefining anything else

#version: "2"
# services:
#   app-native-osx:
#     volumes:
#       - appcode-native-osx-sync:/var/www:nocopy # nocopy is important

# that the important thing
volumes:
  appcode-native-osx-sync:
    external: true
